version: "3.8"

services:
  db:
    image: postgres:15
    container_name: event_postgres_db
    restart: always
    env_file:
      - /.env
    volumes:
      - event_postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  backend:
    build: .
    container_name: event-backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - ./backend/media:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - /.env

volumes:
  event_postgres_db:
